"""
================================================================================
COLLISION PROBABILITY ENGINE  (deterministic, no ML)
================================================================================
Given two space objects, each with a state (position + velocity, TEME km, km/s)
and a position covariance, compute:

    - TCA        time of closest approach (refined, not grid-sampled)
    - miss       miss distance at TCA (km)
    - Pc         probability of collision (Foster 2-D, Chan cross-check)
    - Mahalanobis distance in the encounter plane
    - risk level NOMINAL / ELEVATED / HIGH / CRITICAL

PRIMARY object  : AI-corrected state + calibrated covariance where available.
SECONDARY object: SGP4 state + analytic covariance growth model (debris has no
                  precise truth; this is standard operator practice).

The math (Foster / Chan 2-D Pc):
  1. At TCA, combine covariances:  C = C_primary + C_secondary  (independent).
  2. Project the miss vector and C onto the plane perpendicular to the relative
     velocity (the encounter plane). Motion along v_rel is ignored — the objects
     flash past, so the encounter is effectively instantaneous.
  3. Pc = integral of the 2-D Gaussian N(miss_2d, C_2d) over a disk of radius
     HBR (combined hard-body radius), by Gauss-Legendre quadrature, cross-checked
     against Chan's equivalent-area series.

CORRECTNESS NOTES (things that were wrong before and are now fixed)
-------------------------------------------------------------------
* find_tca() used to clamp the solved TCA into [0, window]. When the caller
  handed it states sampled slightly *after* the true closest approach — which is
  what every screening path did — the clamp pinned the answer to t=0 and the
  function returned the sampled separation as the miss distance. The window is
  now symmetric by default, so an approach in the recent past resolves correctly.

* The quadrature used a rectangle rule whose node count biased Pc high by
  ~0.5%. It is now Gauss-Legendre in radius and a periodic trapezoid in angle,
  which is exact to machine precision for this integrand.

* Chan's series accumulated (v/2)^k / k! directly, which overflows to inf for a
  miss of more than ~40 sigma and returned NaN. Terms are now generated by ratio
  with the exp(-v/2) factor folded in, so the series is stable at any separation.

* secondary_covariance_rtn() was called everywhere with half the screening
  window instead of the actual propagation time to TCA, so a conjunction two
  hours out was assessed with a day and a half of covariance growth. Callers now
  pass the real time span.

This module is pure astrodynamics + statistics — no ML, runs in milliseconds.
================================================================================
"""
from __future__ import annotations

import math
from typing import Sequence, Tuple

import numpy as np

# Industry-standard Pc bands. Read as: below 1e-7 nominal, at or above 1e-4 the
# conjunction is actionable for most operators.
RISK_BANDS = [(1e-7, "NOMINAL"), (1e-5, "ELEVATED"), (1e-4, "HIGH"), (np.inf, "CRITICAL")]

# Below this relative speed the short-encounter (2-D) assumption underpinning
# Foster/Chan stops holding and Pc must be treated as indicative only.
MIN_SHORT_ENCOUNTER_SPEED_KMS = 0.010

# Default hard-body radii (km) when the caller has no better information.
DEFAULT_RADIUS_KM = {"payload": 0.005, "rocket_body": 0.006, "debris": 0.001}


def risk_level(pc: float) -> str:
    for threshold, name in RISK_BANDS:
        if pc < threshold:
            return name
    return "CRITICAL"


def combined_hbr(radius_a_km: float, radius_b_km: float) -> float:
    """Combined hard-body radius: the two objects touch when centres are closer."""
    return float(max(radius_a_km, 0.0) + max(radius_b_km, 0.0))


# ---------------------------------------------------------------- TCA
def find_tca(
    r1: np.ndarray,
    v1: np.ndarray,
    r2: np.ndarray,
    v2: np.ndarray,
    t_window_s: float,
    refine: bool = True,
) -> Tuple[float, float, np.ndarray, np.ndarray]:
    """
    Closest approach under linear relative motion, valid on [-window, +window].

    The window is SYMMETRIC. Callers hand this function states sampled at or near
    a coarse-grid minimum, and the true minimum is as often just behind that
    sample as just ahead of it; the old one-sided clamp silently reported the
    sampled separation whenever the approach had already happened.

    Linear motion is the right model here because the caller is expected to
    supply states already near the approach — over the few minutes that matter,
    curvature contributes far less than SGP4's own error. For a search across
    hours or days, use isdmaas_core.astrodynamics.find_close_approaches, which
    propagates with SGP4 throughout.

    Returns (tca_s, miss_km, relative position at TCA, relative velocity).
    """
    dr = np.asarray(r2, dtype=float) - np.asarray(r1, dtype=float)
    dv = np.asarray(v2, dtype=float) - np.asarray(v1, dtype=float)
    dvv = float(dv @ dv)
    window = abs(float(t_window_s))

    if dvv <= 0.0:
        return 0.0, float(np.linalg.norm(dr)), dr, dv

    t_lin = -float(dr @ dv) / dvv
    t_lin = max(-window, min(window, t_lin))

    if refine:
        # Guard against a caller handing us curved states: sample a fine grid in
        # a narrow span around the analytic solution and keep the best point.
        span = min(120.0, window)
        if span > 0.0:
            lo = max(-window, t_lin - span)
            hi = min(window, t_lin + span)
            if hi > lo:
                ts = np.linspace(lo, hi, 2401)
                d = np.linalg.norm(dr[None, :] + dv[None, :] * ts[:, None], axis=1)
                t_lin = float(ts[int(np.argmin(d))])

    rel = dr + dv * t_lin
    return t_lin, float(np.linalg.norm(rel)), rel, dv


# ---------------------------------------------------------------- encounter plane
def encounter_plane_basis(v_rel: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Orthonormal 2-D basis spanning the plane perpendicular to v_rel."""
    v_rel = np.asarray(v_rel, dtype=float)
    norm = float(np.linalg.norm(v_rel))
    if norm <= 0.0:
        raise ValueError("relative velocity is zero — no encounter plane exists")
    vhat = v_rel / norm
    seed = np.array([1.0, 0.0, 0.0]) if abs(vhat[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
    u1 = seed - (seed @ vhat) * vhat
    u1 /= np.linalg.norm(u1)
    u2 = np.cross(vhat, u1)
    return u1, u2


def project_to_plane(
    rel_pos: np.ndarray, C_combined: np.ndarray, v_rel: np.ndarray
) -> Tuple[np.ndarray, np.ndarray]:
    """Project the miss vector and 3x3 covariance onto the 2-D encounter plane."""
    u1, u2 = encounter_plane_basis(v_rel)
    P = np.stack([u1, u2], axis=0)              # (2,3)
    return P @ np.asarray(rel_pos, dtype=float), P @ np.asarray(C_combined, dtype=float) @ P.T


def _principal_frame(
    miss_2d: np.ndarray, C_2d: np.ndarray
) -> Tuple[float, float, np.ndarray]:
    """Covariance principal axes: returns (sigma_x, sigma_y, miss in that frame)."""
    eigenvalues, eigenvectors = np.linalg.eigh(np.asarray(C_2d, dtype=float))
    # A covariance can come back with a tiny negative eigenvalue from round-off;
    # floor it at a value far below any physically meaningful uncertainty rather
    # than letting a NaN propagate into Pc.
    eigenvalues = np.clip(eigenvalues, 1e-12, None)
    m = eigenvectors.T @ np.asarray(miss_2d, dtype=float)
    return float(np.sqrt(eigenvalues[0])), float(np.sqrt(eigenvalues[1])), m


# ---------------------------------------------------------------- Pc integral
def pc_2d_quadrature(
    miss_2d: np.ndarray, C_2d: np.ndarray, hbr: float, n_r: int = 48, n_theta: int = 128
) -> float:
    """
    Pc = integral over a disk of radius HBR of N(miss_2d, C_2d).

    Gauss-Legendre in radius, periodic trapezoid in angle. The angular rule is
    spectrally accurate for a smooth periodic integrand and the radial rule is
    exact for polynomials up to degree 2*n_r-1, so 48x128 nodes reach machine
    precision on this integrand — far better than the 200x180 rectangle grid
    this replaces, at a quarter of the cost.
    """
    hbr = float(hbr)
    if hbr <= 0.0:
        return 0.0
    sx, sy, m = _principal_frame(miss_2d, C_2d)

    # Gauss-Legendre nodes on [0, hbr] for the radial direction.
    nodes, weights = np.polynomial.legendre.leggauss(n_r)
    rr = 0.5 * hbr * (nodes + 1.0)
    wr = 0.5 * hbr * weights
    th = np.linspace(0.0, 2.0 * np.pi, n_theta, endpoint=False)
    dth = 2.0 * np.pi / n_theta

    R, TH = np.meshgrid(rr, th, indexing="ij")
    x = R * np.cos(TH) - m[0]
    y = R * np.sin(TH) - m[1]
    exponent = -0.5 * ((x / sx) ** 2 + (y / sy) ** 2)
    # Subtracting the peak before exponentiating keeps a far-out conjunction from
    # underflowing the whole integrand to zero before the normalization applies.
    peak = float(exponent.max())
    if peak < -745.0:
        return 0.0
    density = np.exp(exponent - peak)
    integral = float(np.sum(wr[:, None] * density * R) * dth)
    pc = integral * math.exp(peak) / (2.0 * math.pi * sx * sy)
    return float(min(max(pc, 0.0), 1.0))


def _poisson_pmf_array(lam: float, n: int) -> np.ndarray:
    """
    Poisson(lam) probability mass for k = 0..n, evaluated in log space.

    Working in logs is what makes this usable across the whole range the risk
    engine sees. A direct product overflows for lam in the thousands (a miss of
    tens of sigmas) and underflows for lam in the hundreds, and both failures
    land exactly where an operator needs a trustworthy "effectively zero".
    """
    if n < 0:
        return np.zeros(0)
    k = np.arange(n + 1, dtype=float)
    log_factorial = np.concatenate(
        ([0.0], np.cumsum(np.log(np.arange(1, n + 1, dtype=float))))
    ) if n >= 1 else np.array([0.0])
    if lam <= 0.0:
        pmf = np.zeros(n + 1)
        pmf[0] = 1.0
        return pmf
    log_pmf = -lam + k * math.log(lam) - log_factorial
    return np.where(log_pmf > -745.0, np.exp(np.minimum(log_pmf, 0.0)), 0.0)


def pc_chan(miss_2d: np.ndarray, C_2d: np.ndarray, hbr: float) -> float:
    """
    Chan's equivalent-area series Pc — an independent cross-check on the quadrature.

    Chan's result can be written as a mixture of Poisson tails:

        Pc = sum_k  P[N_v = k] * P[N_u > k],     N_v ~ Poisson(v/2), N_u ~ Poisson(u/2)

    with u = HBR^2 / (sigma_x sigma_y) and v the squared Mahalanobis distance.
    Evaluating it this way removes both failure modes of the textbook form:

    * The textbook inner factor is `1 - exp(-u/2) * sum_{j<=k} (u/2)^j / j!`. For
      a small hard-body radius that expression subtracts two numbers that agree
      to sixteen digits, so it bottoms out at machine epsilon — it returned
      2.2e-16 where the true Pc was 1e-36, silently turning a physically
      impossible collision into an apparently real one. The upper Poisson tail is
      the same quantity computed by addition only, so no digits are lost.

    * Accumulating (v/2)^k / k! directly overflows to infinity past roughly a
      40-sigma miss. The log-space pmf above has no such limit.

    The sum only needs terms where the u-tail is non-zero, which bounds the work
    by the hard-body term rather than by the separation.

    KNOWN LIMITATION — this is why it is the cross-check and not the answer.
    Chan circularizes the encounter-plane ellipse to an equivalent area. When the
    covariance is strongly anisotropic AND the hard-body radius is comparable to
    the smaller sigma, that approximation is not merely imprecise: at sigma
    0.02 x 0.5 km with HBR 50 m it reports 1e-48 where the true value is 6.6e-38.
    The quadrature is the reported Pc for exactly this reason, and
    `pc_methods_agree` flags the disagreement instead of hiding it.
    """
    hbr = float(hbr)
    if hbr <= 0.0:
        return 0.0
    sx, sy, m = _principal_frame(miss_2d, C_2d)
    half_u = 0.5 * hbr * hbr / (sx * sy)
    half_v = 0.5 * ((m[0] / sx) ** 2 + (m[1] / sy) ** 2)

    # Range of k over which the u-tail carries any mass at all.
    n_u = int(half_u + 10.0 * math.sqrt(max(half_u, 1.0)) + 60.0)
    pmf_u = _poisson_pmf_array(half_u, n_u)
    # tail_u[k] = P(N_u > k), accumulated from the far end so nothing cancels.
    reverse_sum = np.cumsum(pmf_u[::-1])[::-1]
    tail_u = np.concatenate((reverse_sum[1:], [0.0]))

    # If the v-mass sits entirely above the range where the u-tail is non-zero,
    # every product is zero and Pc is zero to double precision.
    if half_v - 12.0 * math.sqrt(max(half_v, 1.0)) > n_u:
        return 0.0

    pmf_v = _poisson_pmf_array(half_v, n_u)
    return float(min(max(float(np.dot(pmf_v, tail_u)), 0.0), 1.0))


def mahalanobis_2d(miss_2d: np.ndarray, C_2d: np.ndarray) -> float:
    """Miss distance in sigmas. Falls back to the pseudo-inverse if C is singular."""
    miss_2d = np.asarray(miss_2d, dtype=float)
    C_2d = np.asarray(C_2d, dtype=float)
    try:
        quadratic = float(miss_2d @ np.linalg.solve(C_2d, miss_2d))
    except np.linalg.LinAlgError:
        quadratic = float(miss_2d @ np.linalg.pinv(C_2d) @ miss_2d)
    return float(np.sqrt(max(quadratic, 0.0)))


# ------------------------------------------------- secondary covariance model
def secondary_covariance_rtn(
    prop_time_s: float,
    base_sigma_km: Sequence[float] = (0.3, 0.5, 0.3),
    growth_along_km_per_day: float = 2.0,
    growth_radial_km_per_day: float = 0.3,
    growth_normal_km_per_day: float = 0.3,
) -> np.ndarray:
    """
    Analytic covariance growth for an object propagated by SGP4.

    RTN diagonal; along-track dominates because a small period error integrates
    into along-track position error linearly with time. The base sigmas were
    recalibrated for TLE-tracked objects: the earlier, much tighter values put a
    1 km miss at Pc ~ 1e-19, which is not a defensible statement about an object
    whose only tracking source is a public element set.

    `prop_time_s` is the time from the element-set epoch to the assessment, and
    callers must pass the ACTUAL span. Passing a fixed fraction of the screening
    window (the previous behaviour) inflates the covariance of a near-term
    conjunction by more than an order of magnitude.
    """
    days = max(float(prop_time_s), 0.0) / 86400.0
    sr, st, sn = (float(x) for x in base_sigma_km)
    sr += growth_radial_km_per_day * days
    st += growth_along_km_per_day * days
    sn += growth_normal_km_per_day * days
    return np.diag(np.array([sr, st, sn]) ** 2)


def rtn_to_eci_cov(C_rtn: np.ndarray, r: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Rotate an RTN covariance into ECI/TEME using the object's state."""
    r = np.asarray(r, dtype=float)
    v = np.asarray(v, dtype=float)
    r_norm = float(np.linalg.norm(r))
    if r_norm <= 0.0:
        raise ValueError("cannot build an RTN frame at the origin")
    R = r / r_norm
    W = np.cross(r, v)
    w_norm = float(np.linalg.norm(W))
    if w_norm <= 0.0:
        raise ValueError("cannot build an RTN frame from a degenerate state")
    W = W / w_norm
    S = np.cross(W, R)
    basis = np.stack([R, S, W], axis=1)          # columns = RTN axes in ECI
    return basis @ np.asarray(C_rtn, dtype=float) @ basis.T


def eci_to_rtn_cov(C_eci: np.ndarray, r: np.ndarray, v: np.ndarray) -> np.ndarray:
    """Inverse of rtn_to_eci_cov — useful for reporting uncertainty per axis."""
    r = np.asarray(r, dtype=float)
    v = np.asarray(v, dtype=float)
    R = r / np.linalg.norm(r)
    W = np.cross(r, v)
    W = W / np.linalg.norm(W)
    S = np.cross(W, R)
    basis = np.stack([R, S, W], axis=1)
    return basis.T @ np.asarray(C_eci, dtype=float) @ basis


# ---------------------------------------------------------------- top-level
def assess_conjunction(
    r1: np.ndarray,
    v1: np.ndarray,
    C1_eci: np.ndarray,
    r2: np.ndarray,
    v2: np.ndarray,
    C2_eci: np.ndarray,
    hbr_km: float,
    t_window_s: float = 600.0,
    tca_already_refined: bool = False,
) -> dict:
    """
    Full conjunction assessment between primary (1) and secondary (2).

    States in TEME km, km/s; covariances 3x3 ECI km^2; hbr_km combined radius.
    Set `tca_already_refined` when the caller has already located the exact TCA
    (for instance via astrodynamics.refine_candidate) and the states are the
    states AT that time — the linear re-solve is then skipped, which keeps the
    reported miss identical to the refined one instead of perturbing it.

    Returns a CDM-shaped dict.
    """
    if tca_already_refined:
        rel_pos = np.asarray(r2, dtype=float) - np.asarray(r1, dtype=float)
        v_rel = np.asarray(v2, dtype=float) - np.asarray(v1, dtype=float)
        tca = 0.0
        miss = float(np.linalg.norm(rel_pos))
    else:
        tca, miss, rel_pos, v_rel = find_tca(r1, v1, r2, v2, t_window_s)

    rel_speed = float(np.linalg.norm(v_rel))
    short_encounter = rel_speed >= MIN_SHORT_ENCOUNTER_SPEED_KMS

    C_comb = np.asarray(C1_eci, dtype=float) + np.asarray(C2_eci, dtype=float)
    if not short_encounter:
        # The 2-D projection is undefined without a relative-velocity direction,
        # and meaningless when the objects linger together. Report the geometry
        # and say plainly that Pc is not computable under this model.
        return {
            "tca_s_from_epoch": tca,
            "miss_distance_km": miss,
            "radial_miss_km": None,
            "binormal_miss_km": None,
            "pc": None,
            "pc_chan_crosscheck": None,
            "pc_methods_agree": None,
            "mahalanobis": None,
            "hbr_km": float(hbr_km),
            "relative_speed_kms": rel_speed,
            "risk_level": "UNDETERMINED",
            "short_encounter_valid": False,
            "note": (
                "Relative speed below the short-encounter limit "
                f"({MIN_SHORT_ENCOUNTER_SPEED_KMS * 1000:.0f} m/s): the 2-D "
                "Foster/Chan model does not apply. A Monte-Carlo or 3-D "
                "formulation is required for this geometry."
            ),
            "encounter_plane_cov_km2": None,
        }

    miss_2d, C_2d = project_to_plane(rel_pos, C_comb, v_rel)
    pc_quad = pc_2d_quadrature(miss_2d, C_2d, hbr_km)
    pc_series = pc_chan(miss_2d, C_2d, hbr_km)
    maha = mahalanobis_2d(miss_2d, C_2d)

    # Agreement is a relative test with an absolute floor: two methods that both
    # return 1e-30 agree for every practical purpose even if they differ by 50%.
    scale = max(pc_quad, pc_series)
    agree = bool(scale < 1e-12 or abs(pc_quad - pc_series) <= 0.05 * scale)

    return {
        "tca_s_from_epoch": tca,
        "miss_distance_km": miss,
        "radial_miss_km": float(miss_2d[0]),
        "binormal_miss_km": float(miss_2d[1]),
        "pc": pc_quad,
        "pc_method": "foster_2d_gauss_legendre_quadrature",
        "pc_chan_crosscheck": pc_series,
        "pc_methods_agree": agree,
        "mahalanobis": maha,
        "hbr_km": float(hbr_km),
        "relative_speed_kms": rel_speed,
        "risk_level": risk_level(pc_quad),
        "short_encounter_valid": True,
        "encounter_plane_cov_km2": C_2d.tolist(),
    }
